data:extend({

{
    type = "fluid",
    name = "hl-gas-crude",
    icon = "__hyperloopone__/graphics/icons/hl-gas-crude.png",
	default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r = 0.28, g = 0.17, b = 0.03},
    flow_color = {r = 0.28, g = 0.17, b = 0.03},
    max_temperature = 60,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "hl-gas-inert-residual",
    icon = "__hyperloopone__/graphics/icons/hl-gas-inert-residual.png",
	default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r = 0.69, g = 1, b = 1},
    flow_color = {r = 0.69, g = 1, b = 1},
    max_temperature = 60,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-helium-crude",
    icon = "__hyperloopone__/graphics/icons/gas-helium-crude.png",
	default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r = 0.69, g = 1, b = 1},
    flow_color = {r = 0.69, g = 1, b = 1},
    max_temperature = 60,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-helium",
    icon = "__hyperloopone__/graphics/icons/gas-helium.png",
	default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r = 0.69, g = 1, b = 1},
    flow_color = {r = 0.69, g = 1, b = 1},
    max_temperature = 60,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "fluid-helium",
    icon = "__hyperloopone__/graphics/icons/fluid-helium.png",
	default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r = 0.69, g = 1, b = 1},
    flow_color = {r = 0.69, g = 1, b = 1},
    max_temperature = 60,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "hl-used-helium",
    icon = "__hyperloopone__/graphics/icons/hl-used-helium.png",
	default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r = 0.69, g = 1, b = 1},
    flow_color = {r = 0.69, g = 1, b = 1},
    max_temperature = 60,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},

})